version: '3.8'

services:
  copilot_proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: copilot_proxy:latest
    container_name: copilot_proxy_container
    volumes:
      - .:/config  # 映射当前目录下的config文件夹到容器内的/config目录
    environment:
      - DART_VERSION=3.4.1
    network_mode: host  # 使用主机网络配置
